version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins:jenkins
    ports:
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
  db_host:
    container_name: db_host_mysql
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
    ports:
      - "3306:3306"
    expose:
      - 3306
networks:
  net: